### ISSUE TITLE
What is the logic in `make_extra_commit.py`?

### ISSUE THREAD

**Issue by maresb** [conda-forge/automerge-action#10]
### Comment:

I'm working on #9 and trying to test it, but something seems off here.

In the [scripts README](https://github.com/conda-forge/automerge-action/blob/main/scripts/README.md), it says that `cf-test-master` should have both remotes `origin` and `upstream` set to the CF fork of `cf-autotick-bot-test-package-feedstock`. This seems very odd: why have two remotes with the same URL?

Then I try running [`make_extra_commit.py`](https://github.com/conda-forge/automerge-action/blob/main/scripts/make_extra_commit.py). It creates a new branch with a uid-based name, pushes it to `origin` of `cf-test-master`, and then tries to pull it from `upstream` of `cf-autotick-bot-test-package-feedstock`.

I conclude that I need write access to `origin` of `cf-test-master`, and that this should be the same fork as the `upstream` of `cf-autotick-bot-test-package-feedstock`. But setting `cf-autotick-bot-test-package-feedstock` to my fork contradicts Step 5. of the README.

What am I missing here?

**Comment by beckermr** [comment]
Idk what is unclear but the instructions say to add the upstream repo to the fork as a remote called upstream.

**Comment by beckermr** [comment]
And yes you can only run the tests if you have write permissions to upstream.

**Comment by maresb** [comment]
Ah, so that is my problem! :smile: 

How do we proceed? Seems like I have to give up unless someone can help me test #9.

**Comment by beckermr** [comment]
I will push to a branch after code review and test it.

**Comment by maresb** [comment]
In case it helps, here are some feedstocks where this could be live-tested:
https://github.com/conda-forge/boto3-stubs-lite-feedstock/pull/73#issuecomment-1300458884
https://github.com/conda-forge/mypy-boto3-s3-feedstock/pull/160#issuecomment-1299944027
https://github.com/conda-forge/mypy_boto3_rds-feedstock/pull/168#issuecomment-1299682937
https://github.com/conda-forge/mypy_boto3_ec2-feedstock/pull/208#issuecomment-1299577234
